[dependencies]
tokio = { version = "1.0", features = ["full"] }
warp = "0.3"
redis = { version = "0.23", features = ["async-std-comp"] }
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = "1.0"