# Chomp Collectors Schema
---
scrapper: list(include('collector'), required=False)
http_api: list(include('collector'), required=False)
ws_api: list(include('collector'), required=False)
fix_api: list(include('collector'), required=False)
evm_caller: list(include('collector'), required=False)
evm_logger: list(include('collector'), required=False)
solana_caller: list(include('collector'), required=False)
solana_logger: list(include('collector'), required=False)
sui_caller: list(include('collector'), required=False)
sui_logger: list(include('collector'), required=False)
aptos_caller: list(include('collector'), required=False)
aptos_logger: list(include('collector'), required=False)
ton_caller: list(include('collector'), required=False)
ton_logger: list(include('collector'), required=False)
cosmos_caller: list(include('collector'), required=False)
cosmos_logger: list(include('collector'), required=False)

# Base Definitions
---
targettable: &targettable
  name: str() # unique name
  target: str(required=False) # <url> or <chain_id>:<address>, inherited from the parent if undefined
  selector: str(required=False) # web3 event, method, css selector, xpath or nexted attribute, inherited from the parent if undefined
  type: enum('int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32', 'int64', 'uint64', 'float32', 'ufloat32', 'float64', 'ufloat64', 'bool', 'timestamp', 'string', 'binary', 'varbinary', required=False) # inherited from the parent if undefined
  handler: str(required=False)
  reducer: str(required=False)
  headers: map(any(), key=str(), required=False)
  params: any(map(any(), key=str()), list(any()), required=False)
  transient: bool(required=False)
  transformers: list(str(), required=False)

field:
  <<: *targettable

collector:
  <<: *targettable
  interval: enum('s2', 's5', 's10', 's20', 's30', 'm1', 'm2', 'm5', 'm10', 'm15', 'm30', 'h1', 'h4', 'h12', 'D1', 'D2', 'D3', 'W1', 'M1', 'Y1')
  resource_type: enum('timeseries', 'value', 'series', required=False)
  fields: list(include('field'))
